<?php
echo '<!DOCTYPE html>';
echo '';
echo '<!--';
echo 'Date: 19/04/2026';
echo 'Added by: Ayden Rao';
echo 'Description:';
echo 'changed the entire code to have the requiremnts for the assesment.';
echo '';
echo '-->';
echo '';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Group Info</title>';
echo '';
echo '<!-- Link to CSS -->';
echo '<link rel="stylesheet" href="styles/styles.css">';
echo '<link rel="icon" type="image/icon" href="styles/images/WellTech_Logo.PNG">';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
include 'nav.inc';
echo '';
echo '';
echo '';
echo '<!-- Group Info -->';
echo '<section>';
echo '<h1 class="H1exp">Group Information</h1>';
echo '';
echo '<ul>';
echo '<li>';
echo 'Group Name: BestWebDevsInTown';
echo '<ul>';
echo '<li>Class Day: Thursday</li>';
echo '<li>Time: 12:30 PM</li>';
echo '</ul>';
echo '</li>';
echo '</ul>';
echo '</section>';
echo '';
echo '<!-- Contributions -->';
echo '';
echo '<section>';
echo '<h2>Member Contributions</h2>';
echo '';
echo '<div class="team-container">';
echo '';
echo '<div class="card">';
echo '<h3>Panha</h3>';
echo '<p>Home webpage creator and GitHub repository creator.</p>';
echo '<p>Quote (Khmer): "គ្រប់ផ្លូវនាំទៅរ៉ូម។"</p>';
echo '<p>Quote (English): “All roads lead to rome.”</p>';
echo '</div>';
echo '';
echo '<div class="card">';
echo '<h3>Elijah</h3>';
echo '<p>Job description webpage creator and logo design.</p>';
echo '<p>Quote (Italian): "io non parlo inglese."</p>';
echo '<p>Quote (English): "I do not speak english."</p>';
echo '</div>';
echo '';
echo '<div class="card">';
echo '<h3>Robin</h3>';
echo '<p>Apply webpage creator, fixing and checking code.</p>';
echo '<p>Quote (Spanish): "El que lee mucho y anda mucho, ve mucho y sabe mucho." - Miguel de Cervantes</p>';
echo '<p>Quote (English): "He who reads a lot and travels a lot sees a lot and knows a lot."</p>';
echo '</div>';
echo '';
echo '<div class="card">';
echo '<h3>Ayden</h3>';
echo '<p>About webpage creator and Jira board creator.</p>';
echo '<p>Quote (German): "Mosambik hier."</p>';
echo '<p>Quote (English): "Mozambique here."</p>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<!-- Group Photo -->';
echo '<section>';
echo '<h2>Group Photo</h2>';
echo '<figure>';
echo '<img src="images/group_photo.png" alt="Group Photo" width="300">';
echo '<figcaption>"We are the best developers in town"</figcaption>';
echo '</figure>';
echo '</section>';
echo '';
echo '<!-- Fun Facts -->';
echo '<section>';
echo '<h2>Fun Facts</h2>';
echo '';
echo '<table class="fun-facts">';
echo '<thead>';
echo '<tr>';
echo '<th>Name</th>';
echo '<th>Fun Fact</th>';
echo '</tr>';
echo '</thead>';
echo '';
echo '<tbody>';
echo '<tr>';
echo '<td>Panha</td>';
echo '<td>I had both my wisdom teeth taken out at the same time.</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td>Elijah</td>';
echo '<td>If you took 1 step every second for a whole day, you would walk very far.</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td>Robin</td>';
echo '<td>My mother lives in Spain</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td>Ayden</td>';
echo '<td>I am double jointed in 5 spots on my body</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</section>';
echo '<br>';
include 'footer.inc';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>