<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="description" content="Group project for the WellTech Digital Health & Wellness Provider. This page provides the application to apply for a jobn at the company.">';
echo '<meta name="keywords" content="HTML5, CSS layout">';
echo '<meta name="author" content="Robin Ellul Romero">';
echo '<title>Job Application for WellTech</title>';
echo '<link rel="stylesheet" href="styles/styles.css">';
echo '<link rel="icon" type="image/icon" href="styles/images/WellTech_Logo.PNG">';
echo '<style>';
echo '.page-container {';
echo 'max-width: 1200px;';
echo 'margin: auto;';
echo 'padding: 20px;';
echo 'text-align: center;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="page-container">';
include 'header.inc';
echo '<h2 style="font-size: 2.5rem;">Fill out the form below to apply for a position at <b>WellTech</b>.</h2>';
echo '<h2>All fields marked with * are required </h2>';
echo '</div>';
echo '';
echo '<!-- I used generative AI to help me better understand the patterns, but i wrote them myself -->';
echo '';

echo '<form class="application-form" action="process_eoi.php" method="POST" novalidate>';

echo '';
echo '<fieldset>';
echo '<legend>Applicant Details</legend>';
echo '';
echo '<label for="firstname">First Name*:</label>';
echo '<input type="text" name="firstname" id="firstname" pattern="[A-za-z]{1,20}" required>';
echo '<label for="lastname">Last Name*:</label>';
echo '<input type="text" name="lastname" id="lastname" pattern="[A-za-z]{1,20}" required>';
echo '<br>';
echo '<label for="preferredname">Preferred Name:</label>';
echo '<input type="text" name="preferredname" id="preferredname" pattern="[A-za-z]{1,20}">';
echo '<br>';
echo '<label for="dob">Date of Birth*:</label>';
echo '<input type="date" name="dob" id="dob" required>';
echo '<br>';
echo '<fieldset class="subfield">';
echo '<legend class="sublegend">Gender:</legend>';
echo '<input type="radio" name="gender" value="Male" id="male" required> <label for="male">Male</label>';
echo '<input type="radio" name="gender" value="Female" id="female" required><label for="female">Female</label>';
echo '<input type="radio" name="gender" value="Other" id="other" required> <label for="other">Other</label>';
echo '</fieldset>';
echo '<label for="address">Street Address*:</label>';
echo '<input type="text" name="address" id="address" pattern=".{1,40}" required>';
echo '<br>';
echo '';
echo '<label for="town">Town/Suburb*:</label>';
echo '<input type="text" name="town" id="town" pattern=".{1,40}" required>';
echo '<br>';
echo '<label for="state">State*:</label>';
echo '<select name="state" id="state" required>';
echo '<option value="">Select</option>';
echo '<option value="VIC">VIC</option>';
echo '<option value="NSW">NSW</option>';
echo '<option value="QLD">QLD</option>';
echo '<option value="SA">SA</option>';
echo '<option value="WA">WA</option>';
echo '<option value="TAS">TAS</option>';
echo '<option value="ACT">ACT</option>';
echo '<option value="NT">NT</option>';
echo '</select>';
echo '<br>';
echo '<label for="postcode">Postcode*:</label>';
echo '<input type="text" name="postcode" id="postcode" pattern="[0-9]{4}" required>';
echo '';
echo '</fieldset>';
echo '';
echo '';
echo '<fieldset>';
echo '<legend>Job Position</legend>';
echo '';
echo '<label for="position">Position Applying For*:</label>';
echo '<select name="position" id="position" required>';
echo '<option value="">Select Position:</option>';
echo '<option value="software developer">Software Developer</option>';
echo '<option value="It Support specialist">IT Support Specialist</option>';
echo '<option value="Network Engineer">Network Engineer</option>';
echo '<option value="cybersecurity analyst">Cybersecurity Analyst</option>';
echo '<option value="web designer">Web Designer</option>';
echo '</select>';
echo '<br>';
echo '<label for="jobref">Job Reference number*:</label>';
echo '<input type="text" name="jobref" id="jobref" pattern="[A-Za-z0-9]{5}" required>';
echo '<br>';
echo '<fieldset class="subfield">';
echo '<legend class="sublegend">Employment Type</legend>';
echo '<input type="radio" name="employment" value="Full Time" id="fulltime"><label for="fulltime">Full Time</label>';
echo '<input type="radio" name="employment" value="Part Time" id="parttime"><label for="parttime">Part Time</label>';
echo '<input type="radio" name="employment" value="Internship" id="intern"><label for="intern">Internship</label>';
echo '</fieldset>';
echo '</fieldset>';
echo '';
echo '';
echo '<fieldset>';
echo '<legend>Contact Details</legend>';
echo '<label for="mobile">Mobile Number*:</label>';
echo '<input type="tel" name="mobile" placeholder="0412345678" id="mobile" pattern="[0-9]{8,12}" required>';
echo '<br>';
echo '<label for="email">Email Address*:</label>';
echo '<input type="email" name="email" placeholder="example@gmail.com" id="email" required>';
echo '<br>';
echo '<label for="linkedin">LinkedIn Profile:</label>';
echo '<input type="url" name="linkedin" placeholder="https://linkedin.com/in/yourname" id="linkedin" size="40">';
echo '</fieldset>';
echo '';
echo '<fieldset>';
echo '<legend>Experience</legend>';
echo '<label for="experience">Years of Experience:</label>';
echo '<select name="experience" id="experience">';
echo '<option value="0-1 years">0-1 years</option>';
echo '<option value="2-3 years">2-3 years</option>';
echo '<option value="4-5 years">4-5 years</option>';
echo '<option value="5+ years">5+ years</option>';
echo '</select>';
echo '<br>';
echo '<fieldset class="subfield">';
echo '<legend class="sublegend">Skill List:</legend>';
echo '<input type="checkbox" name="skills[]" value="programming" id="programming"> <label for="programming">Programming</label><br>';
echo '<input type="checkbox" name="skills[]" value="webdev" id="webdev"> <label for="webdev">Web Development</label><br>';
echo '<input type="checkbox" name="skills[]" value="techsupport" id="techsupport"> <label for="techsupport">Tech Support</label><br>';
echo '<input type="checkbox" name="skills[]" value="problemsolving" id="problemsolving"> <label for="problemsolving">Problem Solving</label><br>';
echo '<input type="checkbox" name="skills[]" value="teamwork" id="teamwork"> <label for="teamwork">Teamwork</label><br>';
echo '<input type="checkbox" name="skills[]" value="communication" id="communication"> <label for="communication">Communication</label><br>';
echo '<input type="checkbox" name="skills[]" value="projectmanagement" id="projectmanagement"> <label for="projectmanagement">Project Management</label><br>';
echo '</fieldset>';
echo '<label for="otherskills" style="display:block">Other Skills:</label>';
echo '<textarea rows="2" id="otherskills" name="otherskills"></textarea>';
echo '<br>';
echo '<label for="resume">Upload Resume*:</label>';
echo '<input type="file" name="resume" id="resume">';
echo '</fieldset>';
echo '';
echo '<fieldset>';
echo '<legend>Submit Application</legend>';
echo '';
echo '<input type="checkbox" id="confirm" required style="margin-right: 6px;">';
echo '<label for="confirm">  I confirm the information provided is accurate.</label>';
echo '<br><br>';
echo '<input class="submit-btn" type="submit" value="Submit Application" style="width: 100%; padding: 12px; background-color:#99e5ff;">';
echo '';
echo '</fieldset>';
echo '';
echo '</form>';
echo '';
include 'nav.inc';
echo '';
include 'footer.inc';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>