<footer>
    <div class="footer-left">
        <span class="footer-brand">BestWebDevsInTown</span>
        <div class="footer-divider"></div>
        <div class="footer-links">
            <a href="https://aydenrao.atlassian.net/jira/core/projects/BG/board?cloudId=ce8f769f-9671-42e4-b406-1f25b0a991ca&filter=&groupBy=status">Jira</a>
            <a href="https://github.com/Pannnss/Assignment-1">GitHub</a>
            <a href="mailto:info@welltech.com">Email</a>
        </div>
    </div>
    <span class="footer-copy">&copy; 2026</span>
</footer>