<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="description" content="Assignment 1">';
echo '<meta name="keywords" content="HTML, CSS, PHP">';
echo '<meta name="author" content="Group 01 - Panha, Robin, Elijah, Ayden">';
echo '<title>Digital Health & Wellness Provider: WellTech</title>';
echo '<link rel="stylesheet" href="styles/styles.css">';
echo '<link rel="icon" type="image/icon" href="styles/images/WellTech_Logo.PNG">';
echo '';
echo '';
echo '</head>';
echo '';
echo '<body>';
include 'nav.inc';
echo '<section>';
echo '<div class="searchbar">';
echo '<form action="/search" method="get">';
echo '<label for="site-search" class="searchlabel">Search the site</label>';
echo '<input type="search" id="site-search" name="q" placeholder="Search...">';
echo '<button type="submit">Search</button>';
echo '</form>';
echo '</div>';
echo '<h1 class="H1exp">Welcome to WellTech</h1>';
echo '</section>';
echo '<section class="section">';
echo '<h2>About Us</h2>';
echo '<p>A private healthcare technology company expanding its digital services team to support online patient';
echo 'platforms, appointment systems, and health information websites.';
echo '</p>';
echo '<h2>Why apply?</h2>';
echo '<p>Join a collaborative, innovative environment where your work directly improves patient experiences and';
echo 'supports healtcare providers. You’ll be part of a team that values creative problem-solving, continuous';
echo 'learning, while making healthcare more accessible, efficient, and personalized.';
echo '</p>';
echo '<h2>Opportunities</h2>';
echo '<p>Check out the <a class="joblink" href="jobs.html">Job Description</a> page for more information.';
echo '</p>';
echo '</section>';
echo '<table class="metrics-table">';
echo '<tr>';
echo '<th colspan="2">Key Metrics</th>';
echo '</tr>';
echo '<tr>';
echo '<th>Metric</th>';
echo '<th>Value</th>';
echo '</tr>';
echo '<tr>';
echo '<td>Patients served</td>';
echo '<td>100</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Appointments booked</td>';
echo '<td>30</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Current staff</td>';
echo '<td>4</td>';
echo '</tr>';
echo '</table>';
echo '<div class="aboriginal-section">';
echo '<div class="aboriginal">';
echo '<img src="images/pngtree-grunge-aboriginal-flag-vector-aborigines-australia-vector-png-image_5036026.png" alt="Aboriginal flag" class="aboriginal-flag">';
echo '<p class="aboriginal-text">';
echo '<strong>Acknowledgement of Country</strong>';
echo 'WellTech acknowledges the Traditional Custodians of the lands on which we live, learn,';
echo 'and work, and pays respects to Elders past and present. We recognise their continuing';
echo 'connection to land, water, and community.';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<br>';
include 'footer.inc';
echo '</body>';
echo '';
echo '</html>';
?>