<nav class="navbar">
    <div class="nav-container">
        <div class="logo">
        <img src="WellTech_Logo.PNG" alt="WellTech Logo">
    <span>WellTech</span>
    </div>
        <ul class="nav-links">
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="jobs.html">Job Description</a></li>
            <li><a href="apply.html">Apply</a></li>
        </ul>
    </div>
</nav>