<nav class="navbar">
    <div class="nav-container">
        <div class="logo">
        <img src="styles/images/WellTech_Logo.PNG" alt="WellTech Logo">
    <span>WellTech</span>
    </div>
        <ul class="nav-links">
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="jobs.php">Job Description</a></li>
            <li><a href="apply.php">Apply</a></li>
        </ul>
    </div>
</nav>